# insert_user("ezou@mit.edu", 10, True, [])
read_table(user_settings_table)
add_tracked_site("ezou@mit.edu", "taobao.com")
read_table(user_settings_table)
remove_tracked_site("ezou@mit.edu", "baidu.com")
read_table(user_settings_table)
remove_tracked_site("ezou@mit.edu", "taobao.com")
read_table(user_settings_table)
add_tracked_site("ezou@mit.edu", "github.com")
read_table(user_settings_table)